[tool.poetry]
name = "brood-app"
version = "0.1.0"
description = "Brood App: Modular social network inspired by Facebook, Discord style."
authors = ["seriki Yakub  <kubulee.kl@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
streamlit = "^1.26.1"
fastapi = "^0.111.0"
uvicorn = "^0.24.0"
pandas = "^2.1.0"
sqlalchemy = "^2.2.0"
pydantic = "^2.2.0"
requests = "^2.31.0"

[tool.poetry.dev-dependencies]
pytest = "^7.4.0"
black = "^24.3.0"
isort = "^6.0.0"

[build-system]
requires = ["poetry-core>=1.4.0"]
build-backend = "poetry.core.masonry.api"
